version: "3.8"

services:
  postgres:
    image: postgres
    container_name: tcc-postgres
    environment:
      - POSTGRES_USER=assombrados
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=Assombrados
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always

  api:
    container_name: tcc-api
    build: ./api
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres

  app:
    container_name: tcc-app
    build: ./app
    ports:
      - "3000:3000"
    restart: always

volumes:
  pgdata:
